package com.mitchellbosecke;

import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.stream.Collectors;

@Controller
public class RootController {


    /**
     * If they land on the root URL, redirect them to the feeding page.
     */
    @RequestMapping("/")
    public String index() {

        return "redirect:/app/feeding";
    }


    /**
     * This is a catch-all endpoint for our entire UI. Every single request
     * will serve the same index.html file generated by webpack.
     */
    @RequestMapping(value = "/app/**")
    @ResponseBody
    public String app() throws IOException {
        ClassPathResource resource = new ClassPathResource("/webpack/index.html");
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(resource.getInputStream()));
        return bufferedReader.lines().collect(Collectors.joining("\n"));
    }
}
